/**
 * extract.js — 从 index.html 中按函数名切出纯函数源码，生成 harness.js
 *
 * 用法: node jl_test/extract.js
 * 输出: jl_test/harness.js（导出所有目标纯函数）
 *
 * 抽取机制：用正则定位 `function name(` 或 `const name =` 的起始行，
 *           然后对函数体做花括号配对（brace-counting）确定结束位置；
 *           箭头函数则匹配到分号/换行结尾。依赖的辅助函数一并切出。
 */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "index.html");
const OUT = path.join(__dirname, "harness.js");

// ── 1. 读取 index.html ──────────────────────────────────────────────
const html = fs.readFileSync(SRC, "utf-8");
const lines = html.split("\n");

// ── 2. 通用抽取工具 ─────────────────────────────────────────────────

/**
 * 找到包含 pattern 的行号（0-based），返回第一个匹配
 */
function findLine(pattern) {
  for (let i = 0; i < lines.length; i++) {
    if (pattern.test(lines[i])) return i;
  }
  throw new Error("Pattern not found: " + pattern);
}

/**
 * 从 startLine 开始，做花括号配对，返回 [startLine, endLine]（含两端，0-based）
 * 适用于 function xxx() { ... } 形式
 */
function braceMatch(startLine) {
  let depth = 0;
  let started = false;
  for (let i = startLine; i < lines.length; i++) {
    const line = lines[i];
    for (let j = 0; j < line.length; j++) {
      const ch = line[j];
      // 跳过字符串和注释中的花括号（简化处理：只跳过引号内的内容）
      if (ch === "{") { depth++; started = true; }
      else if (ch === "}") { depth--; }
      if (started && depth === 0) return [startLine, i];
    }
  }
  throw new Error("Unmatched braces starting at line " + (startLine + 1));
}

/**
 * 抽取一个 function 声明（含完整花括号体）
 */
function extractFunction(name) {
  const re = new RegExp("\\bfunction\\s+" + name + "\\s*\\(");
  const start = findLine(re);
  const [s, e] = braceMatch(start);
  return lines.slice(s, e + 1).join("\n");
}

/**
 * 抽取一个 const arrow / 表达式赋值（单行或多行直到分号）
 */
function extractConstArrow(name) {
  const re = new RegExp("\\bconst\\s+" + name + "\\s*=");
  const start = findLine(re);
  // 收集到行末的分号为止
  let buf = "";
  for (let i = start; i < lines.length; i++) {
    buf += (i > start ? "\n" : "") + lines[i];
    if (/;\s*$/.test(buf)) break;
  }
  return buf;
}

// ── 3. 抽取所有目标函数及依赖 ───────────────────────────────────────

const chunks = [];

// luLimJL — const arrow
chunks.push("// === luLimJL ===");
chunks.push(extractConstArrow("luLimJL"));

// decTierJL — function declaration
chunks.push("\n// === decTierJL ===");
chunks.push(extractFunction("decTierJL"));

// rmaAtrSeriesJL — helper for zzThJL / zzMergeSmallLegsJL
chunks.push("\n// === rmaAtrSeriesJL (helper) ===");
chunks.push(extractFunction("rmaAtrSeriesJL"));

// zzThJL
chunks.push("\n// === zzThJL ===");
chunks.push(extractFunction("zzThJL"));

// zzMergeSmallLegsJL
chunks.push("\n// === zzMergeSmallLegsJL ===");
chunks.push(extractFunction("zzMergeSmallLegsJL"));

// zzPivotsJL
chunks.push("\n// === zzPivotsJL ===");
chunks.push(extractFunction("zzPivotsJL"));

// jlDayClosedJL
chunks.push("\n// === jlDayClosedJL ===");
chunks.push(extractFunction("jlDayClosedJL"));

// swingStateJL
chunks.push("\n// === swingStateJL ===");
chunks.push(extractFunction("swingStateJL"));

// jlPoolShouldKeepLocalJL — jl-1028 龙池快照覆盖决策纯函数
chunks.push("\n// === jlPoolShouldKeepLocalJL ===");
chunks.push(extractFunction("jlPoolShouldKeepLocalJL"));

// jlFfCacheNewerJL — jl-1027/1028 个股资金缓存择新纯函数
chunks.push("\n// === jlFfCacheNewerJL ===");
chunks.push(extractFunction("jlFfCacheNewerJL"));

// ── 4. 拼装 harness.js ─────────────────────────────────────────────

const preamble = `"use strict";
// Auto-generated by extract.js — DO NOT EDIT MANUALLY
// Source: index.html pure-function extraction
`;

const exports_block = `
// ── Exports ──────────────────────────────────────────────────────────
module.exports = {
  luLimJL,
  decTierJL,
  rmaAtrSeriesJL,
  zzThJL,
  zzMergeSmallLegsJL,
  zzPivotsJL,
  jlDayClosedJL,
  swingStateJL,
  jlPoolShouldKeepLocalJL,
  jlFfCacheNewerJL,
};
`;

const output = preamble + chunks.join("\n") + exports_block;
fs.writeFileSync(OUT, output, "utf-8");

console.log("✓ Generated", path.relative(ROOT, OUT), "(" + output.length + " bytes)");
console.log("  Functions extracted:", [
  "luLimJL", "decTierJL", "rmaAtrSeriesJL",
  "zzThJL", "zzMergeSmallLegsJL", "zzPivotsJL",
  "jlDayClosedJL", "swingStateJL",
  "jlPoolShouldKeepLocalJL", "jlFfCacheNewerJL"
].join(", "));
