"use strict";
// Auto-generated by extract.js — DO NOT EDIT MANUALLY
// Source: index.html pure-function extraction
// === luLimJL ===
    const luLimJL = (c, n2) => /ST/i.test(n2 || "") ? 4.8 : /^(30|68)/.test(String(c || "").replace(/^(sh|sz)/, "")) ? 19.8 : /^(8|4|92)/.test(String(c || "").replace(/^(sh|sz)/, "")) ? 29.8 : 9.8;

// === decTierJL ===
  function decTierJL(s) { // jl-0928-6: 档位精度——ETF/基金(51/15/16/58段)或1元以下票用3位小数, 与ks端dec()同口径
    const p2 = Number(s && s.base) || 0, b2 = String(s && s.code || "").replace(/^(sh|sz|bj)/, "");
    return p2 > 0 && p2 < 1 || /^(51|15|16|56|58)/.test(b2) ? 3 : 2; /* v0.83.3: 补 56 段 ETF；仅显示位数，档位取整(computeTierJL tick2)仍按价格 <1 判断，未改 */
  }

// === rmaAtrSeriesJL (helper) ===
  function rmaAtrSeriesJL(rows) {
    const n = rows.length, outA = new Array(n).fill(0);
    if (n < 15) return outA;
    const trs = [];
    for (let i = 1; i < n; i++) trs.push(Math.max(rows[i].h - rows[i].l, Math.abs(rows[i].h - rows[i - 1].c), Math.abs(rows[i].l - rows[i - 1].c)));
    let v = 0;
    for (let j = 0; j < 14; j++) v += trs[j];
    v /= 14;
    outA[14] = v;
    for (let i = 15; i < n; i++) {
      v = (v * 13 + trs[i - 1]) / 14;
      outA[i] = v;
    }
    return outA;
  }

// === zzThJL ===
  function zzThJL(rows) {
    const atS = rmaAtrSeriesJL(rows);
    return rows.map((r, i) => {
      const a = atS[i];
      return a > 0 && r.c > 0 ? Math.min(0.25, Math.max(0.08, 2.5 * a / r.c)) : 0.12;
    });
  }

// === zzMergeSmallLegsJL ===
  function zzMergeSmallLegsJL(zz, rows) {
    if (!zz || zz.length < 4) return zz;
    const atS = rmaAtrSeriesJL(rows), out = zz.slice();
    let merged = true;
    while (merged && out.length >= 4) {
      merged = false;
      for (let i = 0; i + 1 < out.length; i++) {
        const p1 = out[i].p, p2 = out[i + 1].p, mn = Math.min(p1, p2);
        if (!(mn > 0)) continue;
        const idx = rows.findIndex((r) => String(r.t) === out[i + 1].d), a = idx >= 0 ? atS[idx] : 0, c = idx >= 0 ? rows[idx].c : p2, need = a > 0 && c > 0 ? 1.5 * a / c : 0.12;
        if (Math.abs(p2 - p1) / mn < need) {
          out.splice(i, 2);
          merged = true;
          break;
        }
      }
    }
    return out;
  }

// === zzPivotsJL ===
  function zzPivotsJL(rows, th) {
    const n = rows.length;
    if (n < 3) return [];
    const thAt = Array.isArray(th) ? (i2) => th[i2] || 0.12 : () => th;
    const H = (i) => rows[i].h, L = (i) => rows[i].l;
    const piv = [];
    let dir = 0, eH = H(0), eL = L(0), eHi = 0, eLi = 0;
    for (let i = 1; i < n; i++) {
      const h = H(i), l = L(i);
      if (dir >= 0) {
        if (h > eH) {
          eH = h;
          eHi = i;
        }
        if (eH > 0 && (eH - l) / eH >= thAt(i)) {
          piv.push({ d: String(rows[eHi].t), p: eH, t: "H" });
          dir = -1;
          eL = l;
          eLi = i;
        }
      }
      if (dir <= 0) {
        if (l < eL) {
          eL = l;
          eLi = i;
        }
        if (eL > 0 && (h - eL) / eL >= thAt(i)) {
          piv.push({ d: String(rows[eLi].t), p: eL, t: "L" });
          dir = 1;
          eH = h;
          eHi = i;
        }
      }
    }
    if (dir === 1) piv.push({ d: String(rows[eHi].t), p: eH, t: "h" });
    else if (dir === -1) piv.push({ d: String(rows[eLi].t), p: eL, t: "l" });
    return piv.slice(-6);
  }

// === jlDayClosedJL ===
  function jlDayClosedJL(bars) {
    try {
      const nw = new Date(), td = nw.toLocaleDateString("sv-SE");
      const lt = bars && bars.length ? String(bars[bars.length - 1].t).slice(0, 10) : "";
      if (lt && lt !== td) return true;
      const dow = nw.getDay();
      if (dow === 0 || dow === 6) return true;
      return nw.getHours() * 60 + nw.getMinutes() >= 900;
    } catch (e) {
      return true;
    }
  }

// === swingStateJL ===
  function swingStateJL(bars, liveP, opt) {
    const o = opt || {}, LN = "中波段";
    const fail = (why) => ({ ok: false, layerName: LN, why: why || "", back: [], bounce: [], ext: [] });
    if (!Array.isArray(bars) || bars.length < 10) return fail("bars<10");
    const a = bars.slice();
    const p = Number(liveP), safeP = Number.isFinite(p) && p > 0 ? p : 0;
    let zz;
    try { zz = zzMergeSmallLegsJL(zzPivotsJL(a, zzThJL(a)), a) || []; } catch (eZ) { return fail("zigzag异常"); }
    let L1 = null;
    for (let i = zz.length - 1; i >= 0; i--) if (zz[i].t === "L") { L1 = zz[i]; break; }
    if (!L1 || !(L1.p > 0)) return fail("无已确认前低");
    const idxOfD = (d) => {
      const q = String(d || "").slice(0, 10);
      for (let i = a.length - 1; i >= 0; i--) if (String(a[i].t).slice(0, 10) === q) return i;
      return -1;
    };
    const li = idxOfD(L1.d);
    if (li < 0) return fail("前低日期对不上K线");
    /* 段高：L1 之后已确认的 H 枢轴；没有则用 max(段内最高, 现价, 今日最高) 并标 H1prov=1 */
    let HP = null;
    for (let i = zz.length - 1; i >= 0; i--) {
      if (zz[i].t !== "H") continue;
      if (idxOfD(zz[i].d) > li) { HP = zz[i]; break; }
    }
    let segHi = -Infinity, segHiD = "";
    for (let i = li; i < a.length; i++) {
      const h = Number(a[i].h);
      if (Number.isFinite(h) && h > segHi) { segHi = h; segHiD = String(a[i].t).slice(0, 10); }
    }
    if (!Number.isFinite(segHi)) segHi = 0;
    const todayHi = Number(a[a.length - 1].h) || 0;
    let H1v, H1d, H1i, H1prov = 0;
    if (HP) { H1v = HP.p; H1d = String(HP.d).slice(0, 10); H1i = idxOfD(HP.d); }
    else { H1v = Math.max(segHi, safeP, todayHi); H1d = segHiD; H1i = idxOfD(segHiD); H1prov = 1; }
    if (!(H1v > L1.p)) return fail("段高不高于前低");
    if (H1i < 0) H1i = a.length - 1;
    const rng = H1v - L1.p;
    if (!(rng > 0)) return fail("幅度为0");
    /* ③ 暂定起点：严格晚于段高那根K线的日线最低价 */
    let pullLow = null, pullLowD = "";
    for (let i = H1i + 1; i < a.length; i++) {
      const l = Number(a[i].l);
      if (!Number.isFinite(l)) continue;
      if (pullLow === null || l < pullLow) { pullLow = l; pullLowD = String(a[i].t).slice(0, 10); }
    }
    /* ③ 已确认起点：段高之后被反向确认过的 L 枢轴（取最近一个） */
    let confLow = null, confLowD = "";
    for (let i = zz.length - 1; i >= 0; i--) {
      if (zz[i].t !== "L") continue;
      if (idxOfD(zz[i].d) > H1i) { confLow = zz[i].p; confLowD = String(zz[i].d).slice(0, 10); break; }
    }
    let anchor = null, anchorKind = "none";
    if (confLow !== null) { anchor = confLow; anchorKind = "confirmed"; }
    else if (pullLow !== null) { anchor = pullLow; anchorKind = "provisional"; }
    /* ① 破位：以收盘价为准。未定盘时用现价暂代，只标 intraday，不作废段 */
    const closed = o.closed !== false;
    const lastC = Number(a[a.length - 1].c);
    const refC = closed ? (Number.isFinite(lastC) ? lastC : safeP) : (safeP || (Number.isFinite(lastC) ? lastC : 0));
    let brokeMode = "none";
    if (refC > 0 && refC < L1.p) brokeMode = closed ? "closed" : "intraday";
    const broke = brokeMode === "closed";
    const legDir = broke ? -1 : 1;
    const retrace = safeP > 0 ? (H1v - safeP) / rng : 0;
    const BR = [0.382, 0.5, 0.618, 0.786];
    /* 破位后接回档整组作废（上升段的回撤位在下降段没有意义），改给反弹档 */
    const back = broke ? [] : BR.map((r) => ({ r: r, v: H1v - rng * r, nonSwing: false }));
    let bounce = [];
    const downLow = pullLow;
    if (broke && downLow !== null && H1v > downLow) {
      const rgD = H1v - downLow;
      bounce = BR.map((r) => ({ r: r, v: downLow + rgD * r, nonSwing: false }));
    }
    /* ④ 等幅外推锚在下一段起点 */
    const ext = anchor !== null ? [1.272, 1.618, 2.618].map((r) => ({ r: r, v: anchor + rng * r, nonSwing: true })) : [];
    let msg;
    if (broke) msg = "收盘已破前低 " + L1.p.toFixed(2) + " · 中波段翻转为下降段 " + H1v.toFixed(2) + " → " + (downLow === null ? "—" : downLow.toFixed(2)) + " · 接回档作废，改看反弹档";
    else if (brokeMode === "intraday") msg = "盘中已跌破前低 " + L1.p.toFixed(2) + " · 待收盘确认（插针不算破）";
    else msg = "前低 " + L1.p.toFixed(2) + " 未破（现价高出 " + (safeP > 0 ? ((safeP / L1.p - 1) * 100).toFixed(1) : "—") + "%）· 回吐 " + (retrace * 100).toFixed(0) + "%";
    if (anchorKind === "provisional") msg += " · 暂定起点 " + (pullLow === null ? "—" : pullLow.toFixed(2)) + "（待枢轴成立）";
    else if (anchorKind === "confirmed") msg += " · 已确认起点 " + confLow.toFixed(2);
    if (H1prov) msg += " · 段高未确认";
    return {
      ok: true, layerName: LN, closed: closed, refC: refC,
      L1: L1.p, L1d: String(L1.d).slice(0, 10),
      H1: H1v, H1d: H1d, H1prov: H1prov,
      rng: rng, retrace: retrace,
      pullLow: pullLow, pullLowD: pullLowD,
      confLow: confLow, confLowD: confLowD,
      anchor: anchor, anchorKind: anchorKind,
      broke: broke, brokeMode: brokeMode, legDir: legDir, backInvalid: broke,
      downLow: downLow, downLowD: pullLowD,
      back: back, bounce: bounce, ext: ext, msg: msg
    };
  }

// === jlPoolShouldKeepLocalJL ===
  function jlPoolShouldKeepLocalJL(locD0, ancD0, snapD0) {
    const a = String(locD0 || ""), b = String(ancD0 || ""), s = String(snapD0 || "");
    const best = a > b ? a : b;
    return !!(best && s && best >= s);
  }

// === jlFfCacheNewerJL ===
  function jlFfCacheNewerJL(cacheD0Date, offAsOf) {
    const c = String(cacheD0Date || ""), o = String(offAsOf || "") || "0000";
    return !!(c && c >= o);
  }
// ── Exports ──────────────────────────────────────────────────────────
module.exports = {
  luLimJL,
  decTierJL,
  rmaAtrSeriesJL,
  zzThJL,
  zzMergeSmallLegsJL,
  zzPivotsJL,
  jlDayClosedJL,
  swingStateJL,
  jlPoolShouldKeepLocalJL,
  jlFfCacheNewerJL,
};
